-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 02:26:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lis_final_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lis_final_1` ;

-- -----------------------------------------------------
-- Schema lis_final_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lis_final_1` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema phpmyadmin
-- -----------------------------------------------------
USE `lis_final_1` ;

-- -----------------------------------------------------
-- Table `lis_final_1`.`audit_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`audit_orders` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`audit_orders` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_record` VARCHAR(200) NOT NULL COMMENT 'datos exitentes en el registro modificado JSON',
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `employee_id` INT(10) UNSIGNED NOT NULL,
  `orders_id` INT(10) UNSIGNED NOT NULL,
  `action_records_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `fk_audit_record_users1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_audit_orders_orders1_idx` (`orders_id` ASC) VISIBLE,
  INDEX `fk_audit_orders_action_records1_idx` (`action_records_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar auditorías de cambios en datos de diferentes tablas';


-- -----------------------------------------------------
-- Table `lis_final_1`.`audit_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`audit_result` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`audit_result` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `action_record` ENUM('create', 'update', 'delete') NULL DEFAULT NULL,
  `data_record` VARCHAR(200) NOT NULL COMMENT 'datos exitentes en el registro modificado JSON',
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `users_id` INT(10) UNSIGNED NOT NULL,
  `studie_results_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `studie_results_id`),
  INDEX `fk_audit_record_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_audit_record_studie_results1_idx` (`studie_results_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar auditorías de cambios en datos de diferentes tablas';


-- -----------------------------------------------------
-- Table `lis_final_1`.`audit_studie_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`audit_studie_results` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`audit_studie_results` (
  `id` INT(10) UNSIGNED NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 2 COMMENT 'estados de resultado en 1 valido, 0 no valido 2 en proceso ',
  `values` VARCHAR(250) NULL DEFAULT NULL,
  `values_standard` VARCHAR(250) NULL DEFAULT NULL,
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `date_validate` DATE NULL DEFAULT NULL,
  `observations` VARCHAR(250) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar estudios a relaizar';


-- -----------------------------------------------------
-- Table `lis_final_1`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`states` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`states` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `date_update_at` DATETIME NULL DEFAULT NULL,
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar ciudades';


-- -----------------------------------------------------
-- Table `lis_final_1`.`citys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`citys` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`citys` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `states_id` INT(10) UNSIGNED NOT NULL,
  `date_update_at` DATETIME NULL DEFAULT NULL,
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY USING BTREE (`id`),
  INDEX `fk_citys_states1_idx` (`states_id` ASC) VISIBLE,
  CONSTRAINT `citys_ibfk_1`
    FOREIGN KEY (`states_id`)
    REFERENCES `lis_final_1`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 370
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar ciudades';


-- -----------------------------------------------------
-- Table `lis_final_1`.`doctors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`doctors` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`doctors` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(80) NOT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `date_update_at` DATETIME NULL DEFAULT NULL,
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `license` VARCHAR(45) NOT NULL,
  `phone` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar ciudades';


-- -----------------------------------------------------
-- Table `lis_final_1`.`exams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`exams` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`exams` (
  `id` INT(10) UNSIGNED NOT NULL,
  `detail` VARCHAR(250) NOT NULL,
  `common` VARCHAR(150) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `update_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `lis_final_1`.`medical_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`medical_conditions` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`medical_conditions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Registra condion medica relevante',
  `condition` VARCHAR(80) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0: inactivo 1 activo',
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar estados importantes de un paciente: embarazo, hipertension etc..';


-- -----------------------------------------------------
-- Table `lis_final_1`.`new_audit_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`new_audit_orders` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`new_audit_orders` (
  `id` INT(10) UNSIGNED NOT NULL,
  `diagnostico` VARCHAR(250) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0: inactivo, 1: activo',
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'id de usuario paciente',
  `employee_id` INT(10) UNSIGNED NOT NULL COMMENT 'id de usuarios que crea la orden',
  `doctor_id` INT(10) UNSIGNED NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP())
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `lis_final_1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`users` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(80) NOT NULL,
  `last_name` VARCHAR(80) NOT NULL,
  `gender` CHAR(1) NOT NULL COMMENT 'M: masculino, F: femenino, X: gen x',
  `active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0: inactivo, 1: activo',
  `document` INT(11) NOT NULL,
  `phone` INT(11) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `address` VARCHAR(80) NOT NULL,
  `date_birth_at` DATE NULL DEFAULT NULL,
  `password` VARCHAR(80) NOT NULL,
  `create_users_id` INT(10) UNSIGNED NOT NULL,
  `update_users_id` INT(10) UNSIGNED NOT NULL,
  `cityId` INT(10) UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY USING BTREE (`id`, `update_users_id`, `create_users_id`),
  INDEX `fk_users_citys1_idx` (`cityId` ASC) VISIBLE,
  INDEX `fk_users_users1_idx` (`update_users_id` ASC) VISIBLE,
  CONSTRAINT `ciudades`
    FOREIGN KEY (`cityId`)
    REFERENCES `lis_final_1`.`citys` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `lis_final_1`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`orders` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`orders` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `diagnostico` VARCHAR(250) NOT NULL,
  `comment` VARCHAR(250) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0: inactivo, 1: activo',
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'id de usuario paciente',
  `employee_id` INT(10) UNSIGNED NOT NULL COMMENT 'id de usuarios que crea la orden',
  `doctor_id` INT(10) UNSIGNED NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `empleado` (`employee_id` ASC) VISIBLE,
  INDEX `doctor` (`doctor_id` ASC) VISIBLE,
  INDEX `paciente` (`user_id` ASC) VISIBLE,
  CONSTRAINT `doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `lis_final_1`.`doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado`
    FOREIGN KEY (`employee_id`)
    REFERENCES `lis_final_1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `paciente`
    FOREIGN KEY (`user_id`)
    REFERENCES `lis_final_1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `lis_final_1`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`profiles` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`profiles` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `access_auth` TINYINT(3) UNSIGNED NOT NULL,
  `type` VARCHAR(80) NOT NULL,
  `date_update_at` DATETIME NULL DEFAULT NULL,
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `license` VARCHAR(45) NULL DEFAULT NULL,
  `date_delete_at` VARCHAR(45) NULL DEFAULT NULL,
  `users_id1` INT(10) UNSIGNED NOT NULL,
  `users_update_users_id` INT(10) UNSIGNED NOT NULL,
  `users_create_users_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profiles_users1_idx1` (`users_id1` ASC, `users_update_users_id` ASC, `users_create_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_profiles_users1`
    FOREIGN KEY (`users_id1` , `users_update_users_id` , `users_create_users_id`)
    REFERENCES `lis_final_1`.`users` (`id` , `update_users_id` , `create_users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `lis_final_1`.`samples`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`samples` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`samples` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_update_at` DATETIME NULL DEFAULT NULL,
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valid` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar ciudades';


-- -----------------------------------------------------
-- Table `lis_final_1`.`studies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`studies` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`studies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'estados de estudio TABLA',
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `update_at` DATE NULL DEFAULT NULL,
  `date_validate` DATE NULL DEFAULT NULL,
  `observations` VARCHAR(250) NULL DEFAULT NULL,
  `studie_results_id` INT(10) UNSIGNED NOT NULL,
  `tests_id` INT(10) UNSIGNED NOT NULL,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `exams_id` INT(10) UNSIGNED NOT NULL,
  `samples_id` INT(10) UNSIGNED NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `fk_studies_studie_results1_idx` (`studie_results_id` ASC) VISIBLE,
  INDEX `fk_studies_tests1_idx` (`tests_id` ASC) VISIBLE,
  INDEX `fk_studies_orders1_idx1` (`order_id` ASC) VISIBLE,
  INDEX `fk_studies_exams1_idx` (`exams_id` ASC) VISIBLE,
  INDEX `fk_studies_samples1_idx` (`samples_id` ASC) VISIBLE,
  CONSTRAINT `fk_studies_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `lis_final_1`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studies_exams1`
    FOREIGN KEY (`exams_id`)
    REFERENCES `lis_final_1`.`exams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studies_samples1`
    FOREIGN KEY (`samples_id`)
    REFERENCES `lis_final_1`.`samples` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar estudios a relaizar en un paciente';


-- -----------------------------------------------------
-- Table `lis_final_1`.`studie_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`studie_results` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`studie_results` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` TINYINT(1) NULL DEFAULT 2 COMMENT 'estados de resultado en 1 valido, 0 no valido 2 en proceso ',
  `values` VARCHAR(250) NULL DEFAULT NULL,
  `values_standard` VARCHAR(250) NULL DEFAULT NULL,
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `date_validate` DATE NULL DEFAULT NULL,
  `observations` VARCHAR(250) NULL DEFAULT NULL,
  `studies_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_studie_results_studies1_idx` (`studies_id` ASC) VISIBLE,
  CONSTRAINT `fk_studie_results_studies1`
    FOREIGN KEY (`studies_id`)
    REFERENCES `lis_final_1`.`studies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar estudios a relaizar';


-- -----------------------------------------------------
-- Table `lis_final_1`.`tests_reference_values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`tests_reference_values` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`tests_reference_values` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `reference_value` VARCHAR(50) NOT NULL,
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `observations` VARCHAR(250) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0: inactivo 1 activo',
  `gender` TINYINT(1) NULL DEFAULT NULL,
  `age_min` INT(11) NULL DEFAULT NULL,
  `age_max` INT(11) NULL DEFAULT NULL,
  `pregnant` TINYINT UNSIGNED NOT NULL,
  `tests_id` INT(10) UNSIGNED NOT NULL,
  `value_max` INT(11) NULL DEFAULT NULL,
  `value_min` INT(11) NULL DEFAULT NULL,
  `exams_id` INT(10) UNSIGNED NOT NULL,
  `name_value` VARCHAR(150) NULL,
  PRIMARY KEY (`id`, `pregnant`, `tests_id`),
  INDEX `fk_tests_reference_values_medical_conditions1_idx` (`pregnant` ASC) VISIBLE,
  INDEX `fk_tests_reference_values_tests1_idx` (`tests_id` ASC) VISIBLE,
  INDEX `fk_tests_reference_values_exams1_idx` (`exams_id` ASC) VISIBLE,
  CONSTRAINT `fk_tests_reference_values_exams1`
    FOREIGN KEY (`exams_id`)
    REFERENCES `lis_final_1`.`exams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar valores standard de estudios';


-- -----------------------------------------------------
-- Table `lis_final_1`.`test_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`test_groups` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`test_groups` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `date_create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `observations` VARCHAR(250) NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0: inactivo, 1: activo',
  `tests_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `tests_id`),
  INDEX `fk_test_groups_tests1_idx` (`tests_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para registrar esudios disponibles';


-- -----------------------------------------------------
-- Table `lis_final_1`.`medical_conditions_has_users1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lis_final_1`.`medical_conditions_has_users1` ;

CREATE TABLE IF NOT EXISTS `lis_final_1`.`medical_conditions_has_users1` (
  `medical_conditions_id` INT(10) UNSIGNED NOT NULL,
  `users_id` INT(10) UNSIGNED NOT NULL,
  `users_update_users_id` INT(10) UNSIGNED NOT NULL,
  `users_create_users_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`medical_conditions_id`, `users_id`, `users_update_users_id`, `users_create_users_id`),
  INDEX `fk_medical_conditions_has_users1_users1_idx` (`users_id` ASC, `users_update_users_id` ASC, `users_create_users_id` ASC) VISIBLE,
  INDEX `fk_medical_conditions_has_users1_medical_conditions1_idx` (`medical_conditions_id` ASC) VISIBLE,
  CONSTRAINT `fk_medical_conditions_has_users1_medical_conditions1`
    FOREIGN KEY (`medical_conditions_id`)
    REFERENCES `lis_final_1`.`medical_conditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_conditions_has_users1_users1`
    FOREIGN KEY (`users_id` , `users_update_users_id` , `users_create_users_id`)
    REFERENCES `lis_final_1`.`users` (`id` , `update_users_id` , `create_users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
